"""Add PontoAlimentacao e RegistroNivelSuprimento models

Revision ID: 6e5f352ee6eb
Revises: 
Create Date: 2025-05-24 16:53:34.121508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e5f352ee6eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ponto_alimentacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_identificador', sa.String(length=100), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('tipo_suprimento', sa.Enum('RACAO', 'AGUA', name='tiposuprimento'), nullable=False),
    sa.Column('capacidade_total_estimada', sa.Float(), nullable=True),
    sa.Column('unidade_medida', sa.String(length=10), nullable=True),
    sa.Column('nivel_atual_estimado_percentual', sa.Integer(), nullable=True),
    sa.Column('data_ultima_verificacao', sa.DateTime(), nullable=True),
    sa.Column('data_ultimo_reabastecimento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_identificador')
    )
    op.create_table('registro_nivel_suprimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ponto_alimentacao_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('nivel_percentual_registrado', sa.Integer(), nullable=False),
    sa.Column('reabastecido', sa.Boolean(), nullable=True),
    sa.Column('observacao', sa.String(length=200), nullable=True),
    sa.Column('registrado_por', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['ponto_alimentacao_id'], ['ponto_alimentacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registro_nivel_suprimento')
    op.drop_table('ponto_alimentacao')
    # ### end Alembic commands ###
